ALTER TABLE comment DROP CONSTRAINT IF EXISTS FKS1SLVNKUEMJSQ2KJ4H3VHX7I1;
ALTER TABLE comment DROP CONSTRAINT IF EXISTS fk_comment_post;
ALTER TABLE comment ADD CONSTRAINT fk_comment_post
    FOREIGN KEY (post_id) REFERENCES post(id)
        ON DELETE CASCADE;